version: '3.8'

services:
  auth-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${SUPABASE_DB_HOST}:${SUPABASE_DB_PORT}/${SUPABASE_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${SUPABASE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${SUPABASE_DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - backend

networks:
  backend:

